"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import { SignerProvider } from '@/app/context/signer'
import { ApolloClient, InMemoryCache, ApolloProvider, gql } from '@apollo/client';
import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const client = new ApolloClient({
  uri: 'https://api.studio.thegraph.com/query/63568/nft-market/v0.0.1',
  cache: new InMemoryCache(),
});
if (process.env.NODE_ENV !== "production") {  // Adds messages only in a dev environment
  loadDevMessages();
  loadErrorMessages();
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer />

        <SignerProvider>
        <ApolloProvider client={client}>
          <div>
            {children}
          </div>
          </ApolloProvider>
        </SignerProvider>

      </body>
    </html>
  )
}
